//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Gala</summary>
	[PublishedContentModel("Gala")]
	public partial class Gala : UmbTextPage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Gala";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Gala(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Gala, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Accepting Entries
		///</summary>
		[ImplementPropertyType("acceptingEntries")]
		public bool AcceptingEntries
		{
			get { return this.GetPropertyValue<bool>("acceptingEntries"); }
		}

		///<summary>
		/// Application Closing Date
		///</summary>
		[ImplementPropertyType("applicationClosingDate")]
		public DateTime ApplicationClosingDate
		{
			get { return this.GetPropertyValue<DateTime>("applicationClosingDate"); }
		}
	}
}
