//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Master</summary>
	[PublishedContentModel("umbMaster")]
	public partial class UmbMaster : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "umbMaster";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public UmbMaster(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<UmbMaster, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Description: This will be put in the html description meta-data tag.  Search engines often use this as the description of the page.
		///</summary>
		[ImplementPropertyType("description")]
		public string Description
		{
			get { return this.GetPropertyValue<string>("description"); }
		}

		///<summary>
		/// Hide from search results: If this is ticked, then this page will never show up in a search.
		///</summary>
		[ImplementPropertyType("hideFromSearchResults")]
		public bool HideFromSearchResults
		{
			get { return this.GetPropertyValue<bool>("hideFromSearchResults"); }
		}

		///<summary>
		/// Show when protected?: Normally, protected pages are hidden from the navigation menu when users aren't logged in. If you tick this box, then this item will still be visible but you'll be asked to login when you click on it.
		///</summary>
		[ImplementPropertyType("showInNavigationEvenIfProtected")]
		public bool ShowInNavigationEvenIfProtected
		{
			get { return this.GetPropertyValue<bool>("showInNavigationEvenIfProtected"); }
		}

		///<summary>
		/// Synopsis: When we link to a page, we often give a synopsis. If this is blank, then the first part of the page content will be used as the synopsis.
		///</summary>
		[ImplementPropertyType("synopsis")]
		public string Synopsis
		{
			get { return this.GetPropertyValue<string>("synopsis"); }
		}

		///<summary>
		/// Page title: The page title overrules the name this page was given. So if the page name is "About us" the title could be "About Our Company Name".
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}

		///<summary>
		/// Hide in navigation?: If set to "Yes", this page will be hidden from the navigation menu at the top.
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return this.GetPropertyValue<bool>("umbracoNaviHide"); }
		}
	}
}
