//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Update Notification</summary>
	[PublishedContentModel("UpdateNotification")]
	public partial class UpdateNotification : UmbMaster
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "UpdateNotification";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public UpdateNotification(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<UpdateNotification, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Additional Text: Extra text to put into the email to explain what the chuff this update is about, because it's not always clear.
		///</summary>
		[ImplementPropertyType("additionalText")]
		public string AdditionalText
		{
			get { return this.GetPropertyValue<string>("additionalText"); }
		}

		///<summary>
		/// Page: Which page has been updated
		///</summary>
		[ImplementPropertyType("page")]
		public IPublishedContent Page
		{
			get { return this.GetPropertyValue<IPublishedContent>("page"); }
		}

		///<summary>
		/// Publish Date: You can overrule the date shown on the site by changing it here. If you don't set a date explicitly here then the news item's create date will be shown.
		///</summary>
		[ImplementPropertyType("publishDate")]
		public DateTime PublishDate
		{
			get { return this.GetPropertyValue<DateTime>("publishDate"); }
		}

		///<summary>
		/// Sent Email: This gets set to True when the item is first published and we send out the email mailshot.
		///</summary>
		[ImplementPropertyType("sentEmail")]
		public bool SentEmail
		{
			get { return this.GetPropertyValue<bool>("sentEmail"); }
		}
	}
}
